# Site settings
title: 
header-img: img/home-bg.png
email: sarahyee41@gmail.com
copyright_name: sarahyee41
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  sarahyee41
learn_profile: sarahyee41
email_username: sarahyee41@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
